/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package link.infra.tailor.agent;

public class App {
	public static void main(String[] args) {
		System.out.println("Please launch this JAR as a Java agent on the program you wish to attach Tailor to");
	}
}
